name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Verify Files
        shell: pwsh
        run: |
          # 检查必要文件是否存在
          if (-not (Test-Path sw.js)) {
            Write-Error "Error: sw.js not found!"
            exit 1
          }
          Write-Host "Found sw.js file"
          Get-Content sw.js
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          cname: # 如果你有自定义域名，在这里添加